# Spam/Ham Email Detection

In [1]:
# Workflow of Machine Learning Model
'''
0) Import Important dependencies
1) Setting up the data
2) Creating the Model
3) Training the Model
4) Testing the Model
5) Prediction
'''

'\n0) Import Important dependencies\n1) Setting up the data\n2) Creating the Model\n3) Training the Model\n4) Testing the Model\n5) Prediction\n'

## 1. Import libraries

In [2]:
# Importing Important Dependencies
import numpy as np
import pandas as pd

In [3]:
# Importing LogisticRegression Model(Binary Output)
from sklearn.linear_model import LogisticRegression

In [4]:
# Importing train test split function
from sklearn.model_selection import train_test_split

In [5]:
# Import accuracy function
from sklearn.metrics import accuracy_score

## 2. Load dataset

In [27]:
# Importing the dataset or Load dataset
df = pd.read_csv('Mail_data.csv')
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## 3. Data preprocessing

In [7]:
# Information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [8]:
# Checking null values
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [9]:
# Basic Analysis
# Check the ham/spam emails counts
df['Category'].value_counts().reset_index()

  Category  count
0      ham   4825
1     spam    747

In [10]:
# Label Enconding
# Labelling spam email as 0 and ham emails as 1
# df.loc[df['diagnosis'] == 'B', 'diagnosis'] = 1
df.loc[df['Category'] == 'ham','Category'] = 1
df.loc[df['Category'] == 'spam','Category'] = 0

In [11]:
# Seperating the Mail data into Input Data and Label(Output Data)
X = df['Message']
Y = df['Category']

In [12]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [13]:
Y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

## 4. Train-test-split

In [14]:
# Splitting the data into Training data and Testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(5572,)
(4457,)
(1115,)

In [15]:
# Feature Extraction
# Transforming the text into numeric machine understanding data
from sklearn.feature_extraction.text import TfidfVectorizer
feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english', lowercase = True)

In [16]:
X_train_num = feature_extraction.fit_transform(X_train)
X_test_num = feature_extraction.transform(X_test)

In [17]:
# Convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

## 5. Train Random Forest model

In [28]:
# Training the model
model = LogisticRegression(max_iter = 1000)
model.fit(X_train_num, Y_train)

LogisticRegression(max_iter=1000)

## 6. Evaluate model accuracy

In [20]:
# Evaluating the Trained Model
X_train_prediction = model.predict(X_train_num)
# Finding the accuracy score of training data
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print("Accuracy score of Training data is", training_data_accuracy)

Accuracy score of Training data is 0.9672425398249944

In [21]:
# Evaluating the testing Model
X_test_prediction = model.predict(X_test_num)
# Finding the accuracy score of testing data
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print("Accuracy score of Testing data is", testing_data_accuracy)

Accuracy score of Testing data is 0.9668161434977578

## 7. Predictive system

In [22]:
# Build a predictive system
input_data = ['Click on this link to avail free free free money']
input_data_num = feature_extraction.transform(input_data)

In [29]:
# Making Prediction
prediction = model.predict(input_data_num)
print("Email Text:", input_data[0])

if prediction[0] == 1:
    print("Prediction: Ham Email")
else:
    print("Prediction: Spam Email")

Email Text: Click on this link to avail free free free money
Prediction: Spam Email